name: Test And Publish

on:
  push:
    branches:
      - main

jobs:
  default:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2

      - uses: actions/setup-node@v2
        with:
          node-version: "14.x"
          cache: "yarn"

      - run: yarn install --frozen-lockfile

      - run: yarn lint

      - run: yarn test --ci

      - run: yarn build

      - uses: JS-DevTools/npm-publish@v1
        id: npm_publish
        with:
          token: ${{ secrets.NPM_TOKEN }}
          access: public

      - uses: actions/create-release@v1
        if: steps.npm_publish.outputs.type != 'none'
        id: create_release
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          tag_name: ${{ steps.npm_publish.outputs.version }}
          release_name: ${{ steps.npm_publish.outputs.version }}
